{
  # Robotic system description and bag file info
  "description_file": "/home/mike/catkin_ws/src/calibration/AtlasCarCalibration/atom_calibration/calibrations/ur10e/eye_to_base/ur10e.urdf.xacro",
  "bag_file": "/home/mike/bagfiles/ur10/eye_to_base_2020-02-05-10-47-48.bag",

   # Specify all sensors that are used in the calibration: Each sensor should have:
   # <sensor_name>: {"link": <The frame of the sensor's data. The value of the sensor's message.header.frame_id.>,
   #                 "parent_link": <Parent frame of the transformation to be calibrated.>,
   #                 "child_link" : <Child frame of the transformation to be calibrated.>,
   #                 "topic_name" : <Name of the ros message topic that contains this sensor's data.>
   #                }
   #
    "sensors": {
         "base_camera": {
                "link": "camera_rgb_optical_frame",
                "parent_link": "base_link",
                "child_link": "camera_link",
                "topic_name": "/kinect/rgb/image_color"
        }
    },

    # This section describes the properties of the calibration pattern used
    # for calibration.
    "calibration_pattern" : {
        # The frame id (or link) of the pattern.
        # This link transformation will be optimized.
        "link": "chessboard_link",
        # The parent frame id (or link) of the pattern.
        # For example, in hand-eye calibration the parent link
        # of the pattern can be the end-effector or the base of the arm
        "parent_link": "base_link",
        # Defines if the pattern link is the same in all collections (i.e. fixed=true),
        # or each collection will have its own estimative of the link transformation.
        "fixed": true,
        # The type of pattern used for the calibration.
        # Supported patterns are:
        # - chessboard
        # - charuco
        "pattern_type": "chessboard",
        # If the pattern type is "charuco" you need to define
        # the aruco dictionary used by the pattern.
        # See https://docs.opencv.org/trunk/dc/df7/dictionary_8hpp.html
        "dictionary": "DICT_5X5_100",
        # Mesh file (collada.dae or stl) for showing pattern on rviz
        "mesh_file": "/home/mike/catkin_ws/src/calibration/AtlasCarCalibration/atom_calibration/meshes/charuco_5X5_800x600.dae",
        # The border width from the edge corner to the pattern physical edge.
        # This is used for 3D sensors and lidars.
        "border_size": 0.5,
        # The number of corners the pattern has in the X and Y dimentions.
        # Note: The charuco detector uses the number of squares per dimension in
        # its detector. Internally we add a +1 to Y and X dimensions to account for
        # that. Therfore, the number of corners should be used even for the charuco
        # pattern.
        "dimension": {"x": 9, "y": 6},
        # The length of the a square edge.
        "size": 0.101,
        # The length of the charuco inner marker.
        "inner_size": 0.014
    },

    # Miscellaneous information
    "anchored_sensor": "base_camera",     # Anchor a given sensor, making it immovable during the optimization.
    "world_link": "base_link",             # Frame of reference for the optimization procedure. Must exist in the
                                           # transformation chains of all the sensors which are being calibrated.
    "max_duration_between_msgs": 0.1  # Max time delta between sensor data messages when creating a collection.

}
